version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  redis:
    image: "redis:alpine"
    expose:
      - '6379'
  celery:
    image: valm/diva_cloud
    command: celery -A celery_tasks worker -l info -P eventlet
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
  web:
    image: valm/diva_cloud
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
